### ISSUE TITLE
Internal error when where clause contains a comparison with a string containing --

### ISSUE THREAD

**Issue by nfsantos** [raw-db/ldb#22]
Works with a single -. Also fails if -- appears as part of a large string.

```
select * from authors where title = "--"

Query: [select * from authors where title = "--"]
Exception: internal error (cpu_info sees 1 sockets and 8 cores
)
INFO:werkzeug:192.168.59.103 - - [13/Aug/2015 14:49:49] "POST /query HTTP/1.1" 500 -
```

**Comment by nfsantos** [comment]
Typing "--" as query also crashes the backend.

**Comment by bgaidioz** [comment]
This is because our python server removes comments with a brute force regexp. In fact now comments are parsed out in OQL, we don't need to process the string in the python server. I remove it and removed the newline replacement too so that it works.
