### ISSUE TITLE
query not working

### ISSUE THREAD

**Issue by bgaidioz** [raw-db/ldb#7]
select I.gender, (select country, count(partition) from I.people P group by country:P.country) as G from (
select gender, (select P from partition) as people from patients P group by gender: P.gender
) I

fails in Scala execution after generating code:

java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at raw.RawImpl.recordTypeSym(Raw.scala:80)

**Comment by bgaidioz** [comment]
A similar one (actually almost the same but it is in case).
select T.gender, (select city, (select patient_id from partition) as c from T.people P group by city: P.city) as X from
(select gender, (select p from partition) as people from patients p group by gender: p.gender) T

**Comment by nfsantos** [comment]
Closed raw-db/raw@37a33bc309faf15a76dcee1224e1c30a86abbbaf

**Comment by nfsantos** [comment]
Closed raw-db/raw@37a33bc309faf15a76dcee1224e1c30a86abbbaf
